### ISSUE TITLE
Create RBAC and service account, and attach it to deployment

### ISSUE THREAD

**Issue by vinicyusmacedo** [luizalabs/mitose#17]
In order for mitose to watch changes to configmaps, we need to create a service account and bind RBAC rules to it. It's good to add it to the documentation and maybe to the yaml we have on the repo:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mitose
  namespace: mitose
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mitose
  namespace: mitose
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mitose
subjects:
- kind: ServiceAccount
  name: mitose
  namespace: mitose
```

And also attach the service account to the deployment.
